# Generated by Django 3.0 on 2019-12-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='File field')),
                ('encrypted', models.CharField(max_length=64, verbose_name='Encrypted Value')),
            ],
        ),
    ]
