# Generated by Django 3.0 on 2019-12-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
